zabbix-server:
  image: 192.168.18.250:5002/appsoar/zabbix-server
  restart: always
  ports:
   - 10051:10051
   - 10052:10052
   - 2812:2812
   - 8082:80
  volumes:
   - /etc/localtime:/etc/localtime:ro
