logspout:
  restart: always
  environment:
    LOGSPOUT: 'ignore'
  volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  command: ${route_uri}
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: 192.168.18.250:5002/appsoar/logspout
  stdin_open: true
