.catalog:
  name: Logspout
  version: 1.0.0
  description: |
    Logspout is a log router for Docker containers.
  questions:
    - variable: "route_uri"
      label: "Logspout推送日志的路由地址"
      type: "string"
      required: true
      default: "syslog://127.0.0.1:5000"
      description: |
        这是所有容器日志被推送的路由地址
