jbosslb:
  ports:
  - ${lb_port}:8080
  tty: true
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
  image: rancher/load-balancer-service
  links:
  - jboss:jboss
  stdin_open: true
jboss:
  environment:
    WAR_URL: ${war_url}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 192.168.18.250:5002/appsoar/jboss
  stdin_open: true
