zabbix-agent:
  image: 192.168.18.250:5002/appsoar/zabbix-agent-xxl-limited:latest
  restart: always
  hostname: ${agent_hostname}
  labels:
      io.rancher.scheduler.global: 'true'
  ports:
   - 10050:10050
  environment:
   - ZA_Server=${zabbix_serverip}
   - ZA_ServerActive=${zabbix_serverip_active}
  volumes:
   - /:/rootfs
   - /etc/localtime:/etc/localtime:ro
